name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - develop
      - qa      
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - develop
      - qa  

permissions:
  contents: read
  pull-requests: write   

jobs:
  build_and_deploy:
    environment: development
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
      # Descargar el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar Node.js con caché
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'   # Angular 19 requiere Node 20.x o superior
          cache: 'npm'

      # Limpiar cache de npm
      - name: Clean npm cache
        run: |
          npm cache clean --force
          npx clear-npx-cache
          
      # Instalar dependencias
      - name: Install dependencies
        run: npm install
        
      # Compilar el proyecto Angular en modo producción
      - name: Build Angular app
        run: npm run build -- --configuration production

      # Copiar archivo de configuración SWA al build
      - name: Copy staticwebapp.config.json
        run: cp staticwebapp.config.json dist/factura-pendiente/browser/

      # Guardar el build como artefacto en GitHub Actions
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: portal-integral-build
          path: dist/factura-pendiente/browser

      # Desplegar en Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"                     
          output_location: "dist/factura-pendiente/browser"

           # Job para QA (depende de que Dev termine bien)
  deploy_qa:
    environment: qa
    runs-on: ubuntu-latest
    needs: build_and_deploy   # Solo corre si el job anterior fue exitoso

    steps:
      # Descargar artefacto generado en el job anterior
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: portal-integral-build

      # Desplegar en Azure Static Web Apps (QA)
      - name: Deploy to Azure Static Web Apps (QA)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_QA }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"                     
          output_location: "portal-integral-build"